services:
  mockoon:
    build:
      context: .
      dockerfile: Dockerfile
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    depends_on:
      - postgres
    restart: always
    ports:
      - 80:8080 # API
      - 81:8081 # WebSocket
      - '3000-3020:3000-3020' # Mockoon Instances Ports
    deploy:
      replicas: 1
    environment:
      - WEB_FULL_URL=http://localhost:80
      - WS_FULL_URL=http://localhost:81
      - AUTH_PROVIDER=disabled
      - NODE_ENV=production
      - DB_DRIVER=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=mockoon
      - DB_USER=mockoon
      - DB_PASSWORD=mockoon

    networks:
      - db
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: mockoon
      POSTGRES_PASSWORD: mockoon
      POSTGRES_DB: mockoon
    networks:
      - db

networks:
  db:
    name: db
