services:
  mockoon:
    build:
      context: .
      dockerfile: Dockerfile
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    restart: always
    volumes:
      - ./data:/data
    ports:
      - 80:8080 # API
      - 81:8081 # WebSocket
      - '3000-4000:3000-4000' # Mockoon Instances Ports
    deploy:
      replicas: 1
    environment:
      - WEB_FULL_URL=http://localhost:80
      - WS_FULL_URL=http://localhost:81
      - DB_PATH_SQLITE=/data
      - AUTH_PROVIDER=disabled
      - NODE_ENV=production
      - DB_DRIVER=sqlite
