import { Frequency, Plans, TeamRoles } from '@mockoon/cloud'

export const DEFAULT_PLAN = {
	plan: Plans.FREE,
	teamId: 'none',
	teamRole: 'user' as TeamRoles,
	deployInstancesQuota: 0,
	deployInstancesQuotaUsed: 0,
	cloudSyncItemsQuota: 0,
	cloudSyncItemsQuotaUsed: 0,
	cloudSyncSizeQuota: 0,
	cloudSyncHighestMajorVersion: 1,
	templatesQuota: 0,
	templatesQuotaUsed: 0,
	nextQuotaResetOn: 0,
	subscription: {
		trial: false,
		provider: 'free' as const,
		frequency: Frequency.YEARLY,
		createdOn: 1744777380227,
		renewOn: 4079996600352,
		portalEnabled: true,
		cancellationScheduled: false,
		pastDue: false,
		subscriptionId: 'none',
	},
}

export const SERVICE_ROLE = {
	id: 'service-role',
	uid: 'service-role',
	email: 'service-role',
	plan: 'ENTERPRISE',
	teamId: 'F1',
	teamRole: 'owner',
	deployInstancesQuota: 10,
	deployInstancesQuotaUsed: 0,
	cloudSyncItemsQuota: 999,
	cloudSyncItemsQuotaUsed: 0,
	cloudSyncSizeQuota: 100000000, // 100MB
	cloudSyncHighestMajorVersion: 1,
	templatesQuota: 999,
	templatesQuotaUsed: 0,
	nextQuotaResetOn: 1,
	subscription: {
		trial: false,
		provider: 'manual',
		frequency: 'YEARLY',
		createdOn: 1744777380227,
		renewOn: 4079996600352,
		portalEnabled: true,
		cancellationScheduled: false,
		pastDue: false,
		subscriptionId: 'F1',
	},
	displayName: 'Admin Service Role',
}

export const DISABLED_AUTH_USER = {
	plan: 'ENTERPRISE',
	teamId: 'F1',
	teamRole: 'owner',
	deployInstancesQuota: 10,
	deployInstancesQuotaUsed: 0,
	cloudSyncItemsQuota: 999,
	cloudSyncItemsQuotaUsed: 0,
	cloudSyncSizeQuota: 100000000, // 100MB
	cloudSyncHighestMajorVersion: 1,
	templatesQuota: 999,
	templatesQuotaUsed: 0,
	nextQuotaResetOn: 1,
	subscription: {
		trial: false,
		provider: 'manual',
		frequency: 'YEARLY',
		createdOn: 1744777380227,
		renewOn: 4079996600352,
		portalEnabled: true,
		cancellationScheduled: false,
		pastDue: false,
		subscriptionId: 'F1',
	},
}
